directories:
  output: release
  buildResources: resources
files:
  - filter:
      - '!.git/'
      - '!installer/'
win:
  appId: ETIS Pohoda
  artifactName: ETIS-Pohoda-setup.${ext}
  icon: ./logo_blue.ico
  publish:
    provider: generic
    url: https://some-url/
    publishAutoUpdate: true
    channel: latest
electronVersion: 25.0.1
